# Generated by Django 4.0.8 on 2022-11-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituition',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instituition',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
