# Generated by Django 4.0.8 on 2022-11-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instituition_id',
            new_name='instituition',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='instituition_id',
            new_name='instituition',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='instituition_id',
            new_name='instituition',
        ),
    ]
