# Generated by Django 4.0.8 on 2022-11-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_faculty_id_alter_instituition_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='instituition',
        ),
        migrations.RemoveField(
            model_name='student',
            name='instituition',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Instituition',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
