# Generated by Django 4.0.8 on 2022-11-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('instituition', models.ForeignKey(blank=True, db_column='instituition_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='instituition.instituition')),
            ],
        ),
    ]
