# Generated by Django 4.0.8 on 2022-11-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
